import { StyleSheet } from 'react-native';

export default styles = StyleSheet.create({
  viroContainer: {
    flex: 1,
    backgroundColor: 'black',
  },
  outer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'black',
  },
  inner: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: 'black',
  },
  titleText: {
    paddingTop: 15,
    paddingBottom: 20,
    color: '#fff',
    textAlign: 'center',
    fontSize: 25,
  },
  buttonText: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 20,
  },
  buttons: {
    height: 60,
    width: 150,
    paddingTop: 10,
    paddingBottom: 10,
    marginTop: 10,
    marginBottom: 10,
    backgroundColor: '#68a0cf',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#fff',
  },
  exitButton: {
    height: 50,
    width: 100,
    paddingTop: 10,
    paddingBottom: 10,
    marginTop: 10,
    marginBottom: 10,
    backgroundColor: '#68a0cf',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#fff',
  },
  tinyLogo: {
    height: 100,
    width: 200,
    resizeMode: 'contain',
  },
  largeLogo: {
    height: 200,
    width: 400,
    resizeMode: 'contain',
  },
  card: {
    // borderRadius: 20,
    flex: 1,
    padding: 10,
    overflow: 'hidden',
    borderColor: 'black',
    borderWidth: 1,
    backgroundColor: 'white',
  },
  projectCard: {
    borderRadius: 30,
    padding: 10,
    marginTop: 5,
    marginBottom: 5,
    overflow: 'hidden',
    borderColor: 'black',
    borderWidth: 1,
    backgroundColor: 'white',
  },
  input: {
    color: 'white',
  },
});
